language: generic

matrix:
  include:
    # Testes no Ubuntu 16.04
    - os: linux
      dist: xenial
      addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - make
           - texlive
           - texlive-latex-extra
           - texlive-science
           - texlive-publishers
           - texlive-lang-portuguese
           - latexmk

script:
     - make all-test
